on:
  push:
    branches:
      - main
jobs:
  ci:
    if: ${{ ! contains(github.event.head_commit.message, '[skip') }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '22'
      - name: Checkout
        uses: actions/checkout@master
      - name: Create env file
        run: |
          touch .env
          echo YADISK_TOKEN=${{ secrets.YADISK_TOKEN }} >> .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Prepare server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          script: |
            cd ${{ secrets.DEPLOY_SERVER_TARGET }}
            systemctl stop aromachef
            rm -rf build
      - name: Copy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          source: build/*
          target: ${{ secrets.DEPLOY_SERVER_TARGET }}
      - name: Finalize server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          script: |
            systemctl start aromachef
