on:
  push:
    branches:
      - main
jobs:
  Lint:
    if: ${{ ! contains(github.event.head_commit.message, '[skip') }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '22'
      - name: Checkout
        uses: actions/checkout@master
      - name: Create env file
        run: |
          touch .env
          echo YADISK_TOKEN=${{ secrets.YADISK_TOKEN }} >> .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
