on:
  push:
    branches:
      - main
jobs:
  ci:
    if: ${{ ! contains(github.event.head_commit.message, '[skip') }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '22'
      - name: Checkout
        uses: actions/checkout@master
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Copy to server
        if: ${{ contains(github.event.head_commit.message, '[deploy]') }}
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          source: public/*,server/*,tools/*,package*.json
          target: ${{ secrets.DEPLOY_SERVER_TARGET }}
      - name: Modify server
        if: ${{ contains(github.event.head_commit.message, '[deploy]') }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          script: |
            cd ${{ secrets.DEPLOY_SERVER_TARGET }}
            npm ci --omit=dev
            systemctl restart app-aromachef
